name: streamlit
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - time
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - streamlit